package com.pat.service.news;

import java.util.List;

/**
 * Built-in RSS/Atom catalogue. Curated, not exhaustive: well-known public
 * feeds that tend to stay stable. Users can add more by URL or keyword.
 */
final class RssFeedCatalog {

    private RssFeedCatalog() {}

    static List<RssFeed> defaults() {
        return List.of(
                // --- Courrier International ---
                f("ci-all", "Courrier International — Tout",
                        "https://www.courrierinternational.com/feed/all/rss.xml",
                        "https://www.courrierinternational.com/", "general", "fr", "fr",
                        "Toute l'actualité internationale traduite."),
                f("ci-france", "Courrier International — France",
                        "https://www.courrierinternational.com/feed/rubrique/france/rss.xml",
                        "https://www.courrierinternational.com/france", "general", "fr", "fr",
                        "La France vue par la presse étrangère."),
                f("ci-geo", "Courrier International — Géopolitique",
                        "https://www.courrierinternational.com/feed/rubrique/geopolitique/rss.xml",
                        "https://www.courrierinternational.com/", "general", "fr", "fr",
                        "Géopolitique."),
                f("ci-eco", "Courrier International — Économie",
                        "https://www.courrierinternational.com/feed/rubrique/economie/rss.xml",
                        "https://www.courrierinternational.com/", "business", "fr", "fr",
                        "Économie internationale."),
                f("ci-societe", "Courrier International — Société",
                        "https://www.courrierinternational.com/feed/rubrique/societe/rss.xml",
                        "https://www.courrierinternational.com/", "general", "fr", "fr",
                        "Société."),
                f("ci-culture", "Courrier International — Culture",
                        "https://www.courrierinternational.com/feed/rubrique/culture/rss.xml",
                        "https://www.courrierinternational.com/", "entertainment", "fr", "fr",
                        "Culture."),
                f("ci-science", "Courrier International — Sciences & environnement",
                        "https://www.courrierinternational.com/feed/rubrique/science-environnement/rss.xml",
                        "https://www.courrierinternational.com/", "science", "fr", "fr",
                        "Sciences et environnement."),

                // --- France ---
                f("lemonde-une", "Le Monde — À la une",
                        "https://www.lemonde.fr/rss/une.xml",
                        "https://www.lemonde.fr/", "general", "fr", "fr", "Une du Monde."),
                f("lemonde-intl", "Le Monde — International",
                        "https://www.lemonde.fr/international/rss_full.xml",
                        "https://www.lemonde.fr/international/", "general", "fr", "fr", "International."),
                f("lemonde-planete", "Le Monde — Planète",
                        "https://www.lemonde.fr/planete/rss_full.xml",
                        "https://www.lemonde.fr/planete/", "science", "fr", "fr", "Climat et environnement."),
                f("lemonde-eco", "Le Monde — Économie",
                        "https://www.lemonde.fr/economie/rss_full.xml",
                        "https://www.lemonde.fr/economie/", "business", "fr", "fr", "Économie."),
                f("lemonde-sport", "Le Monde — Sport",
                        "https://www.lemonde.fr/sport/rss_full.xml",
                        "https://www.lemonde.fr/sport/", "sports", "fr", "fr", "Sport."),
                f("lemonde-sciences", "Le Monde — Sciences",
                        "https://www.lemonde.fr/sciences/rss_full.xml",
                        "https://www.lemonde.fr/sciences/", "science", "fr", "fr", "Sciences."),
                f("lemonde-pixels", "Le Monde — Pixels",
                        "https://www.lemonde.fr/pixels/rss_full.xml",
                        "https://www.lemonde.fr/pixels/", "technology", "fr", "fr", "Numérique."),
                f("figaro", "Le Figaro",
                        "https://www.lefigaro.fr/rss/figaro_actualites.xml",
                        "https://www.lefigaro.fr/", "general", "fr", "fr", "Actualités Le Figaro."),
                f("liberation", "Libération",
                        "https://www.liberation.fr/arc/outboundfeeds/rss/?outputType=xml",
                        "https://www.liberation.fr/", "general", "fr", "fr", "Libération."),
                f("franceinfo", "Franceinfo",
                        "https://www.francetvinfo.fr/titres.rss",
                        "https://www.francetvinfo.fr/", "general", "fr", "fr", "Titres Franceinfo."),
                f("france24-fr", "France 24 (FR)",
                        "https://www.france24.com/fr/rss",
                        "https://www.france24.com/fr/", "general", "fr", "fr", "France 24 en français."),
                f("rfi", "RFI",
                        "https://www.rfi.fr/fr/rss",
                        "https://www.rfi.fr/", "general", "fr", "fr", "Radio France Internationale."),
                f("bfmtv", "BFMTV",
                        "https://www.bfmtv.com/rss/news-24-7/",
                        "https://www.bfmtv.com/", "general", "fr", "fr", "BFMTV 24/7."),
                f("20minutes", "20 Minutes",
                        "https://www.20minutes.fr/feeds/rss-une.xml",
                        "https://www.20minutes.fr/", "general", "fr", "fr",
                        "Une de 20 Minutes."),
                f("ouestfrance", "Ouest-France",
                        "https://www.ouest-france.fr/rss.xml",
                        "https://www.ouest-france.fr/", "general", "fr", "fr", "Ouest-France."),
                f("lesechos", "Les Échos",
                        "https://services.lesechos.fr/rss/les-echos-une.xml",
                        "https://www.lesechos.fr/", "business", "fr", "fr", "Une des Échos."),
                f("latribune", "La Tribune",
                        "https://www.latribune.fr/rss.xml",
                        "https://www.latribune.fr/", "business", "fr", "fr", "La Tribune."),
                f("challenges", "Challenges",
                        "https://www.challenges.fr/rss.xml",
                        "https://www.challenges.fr/", "business", "fr", "fr", "Challenges."),
                f("lequipe", "L'Équipe",
                        "https://www.lequipe.fr/rss/actu_rss.xml",
                        "https://www.lequipe.fr/", "sports", "fr", "fr", "L'Équipe."),
                f("huffpost-fr", "HuffPost France",
                        "https://www.huffingtonpost.fr/feeds/index.xml",
                        "https://www.huffingtonpost.fr/", "general", "fr", "fr", "HuffPost."),
                f("lacroix", "La Croix",
                        "https://www.la-croix.com/RSS/UNIVERS",
                        "https://www.la-croix.com/", "general", "fr", "fr", "La Croix."),
                f("humanite", "L'Humanité",
                        "https://www.humanite.fr/rss.xml",
                        "https://www.humanite.fr/", "general", "fr", "fr", "L'Humanité."),

                // --- Suisse / local ---
                f("rts", "RTS Info",
                        "https://www.rts.ch/info/tout-le-fil/rss.html",
                        "https://www.rts.ch/info/", "general", "fr", "ch", "Radio Télévision Suisse."),
                f("letemps", "Le Temps",
                        "https://www.letemps.ch/articles.rss",
                        "https://www.letemps.ch/", "general", "fr", "ch", "Le Temps (Genève)."),
                f("24heures", "24 heures",
                        "https://www.24heures.ch/latest/rss",
                        "https://www.24heures.ch/", "general", "fr", "ch", "24 heures (Vaud)."),
                f("tdg", "Tribune de Genève",
                        "https://www.tdg.ch/latest/rss",
                        "https://www.tdg.ch/", "general", "fr", "ch", "Tribune de Genève."),
                f("nzz", "NZZ",
                        "https://www.nzz.ch/recent.rss",
                        "https://www.nzz.ch/", "general", "de", "ch", "Neue Zürcher Zeitung."),
                f("20min-ch", "20 Minuten",
                        "https://www.20min.ch/rss/index/front",
                        "https://www.20min.ch/", "general", "de", "ch", "20 Minuten."),

                // --- Tech FR ---
                f("numerama", "Numerama",
                        "https://www.numerama.com/feed/",
                        "https://www.numerama.com/", "technology", "fr", "fr", "Numerama."),
                f("next", "Next",
                        "https://next.ink/feed/",
                        "https://next.ink/", "technology", "fr", "fr", "Next (ex NextINpact)."),
                f("frandroid", "Frandroid",
                        "https://www.frandroid.com/feed",
                        "https://www.frandroid.com/", "technology", "fr", "fr", "Frandroid."),
                f("journaldugeek", "Journal du Geek",
                        "https://www.journaldugeek.com/feed/",
                        "https://www.journaldugeek.com/", "technology", "fr", "fr", "Journal du Geek."),
                f("korben", "Korben",
                        "https://korben.info/feed",
                        "https://korben.info/", "technology", "fr", "fr", "Korben."),
                f("linuxfr", "LinuxFr",
                        "https://linuxfr.org/news.atom",
                        "https://linuxfr.org/", "technology", "fr", "fr", "LinuxFr.org."),
                f("zdnet-fr", "ZDNet France",
                        "https://www.zdnet.fr/feeds/rss/actualites/",
                        "https://www.zdnet.fr/", "technology", "fr", "fr", "ZDNet."),

                // --- Science FR ---
                f("futura", "Futura Sciences",
                        "https://www.futura-sciences.com/rss/actualites.xml",
                        "https://www.futura-sciences.com/", "science", "fr", "fr", "Futura."),
                f("sciav", "Sciences et Avenir",
                        "https://www.sciencesetavenir.fr/rss.xml",
                        "https://www.sciencesetavenir.fr/", "science", "fr", "fr", "Sciences et Avenir."),
                f("cnrs", "CNRS Le Journal",
                        "https://lejournal.cnrs.fr/rss",
                        "https://lejournal.cnrs.fr/", "science", "fr", "fr", "CNRS."),
                f("pourlascience", "Pour la Science",
                        "https://www.pourlascience.fr/rss.xml",
                        "https://www.pourlascience.fr/", "science", "fr", "fr", "Pour la Science."),

                // --- English news ---
                f("bbc-world", "BBC News — World",
                        "https://feeds.bbci.co.uk/news/world/rss.xml",
                        "https://www.bbc.com/news/world", "general", "en", "gb", "BBC World."),
                f("bbc-tech", "BBC News — Technology",
                        "https://feeds.bbci.co.uk/news/technology/rss.xml",
                        "https://www.bbc.com/news/technology", "technology", "en", "gb", "BBC Technology."),
                f("bbc-science", "BBC News — Science",
                        "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
                        "https://www.bbc.com/news/science_and_environment", "science", "en", "gb",
                        "BBC Science & Environment."),
                f("guardian-world", "The Guardian — World",
                        "https://www.theguardian.com/world/rss",
                        "https://www.theguardian.com/world", "general", "en", "gb", "The Guardian."),
                f("guardian-tech", "The Guardian — Technology",
                        "https://www.theguardian.com/uk/technology/rss",
                        "https://www.theguardian.com/uk/technology", "technology", "en", "gb",
                        "Guardian Technology."),
                f("nyt-world", "New York Times — World",
                        "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
                        "https://www.nytimes.com/section/world", "general", "en", "us", "NYT World."),
                f("nyt-tech", "New York Times — Technology",
                        "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",
                        "https://www.nytimes.com/section/technology", "technology", "en", "us", "NYT Tech."),
                f("nyt-science", "New York Times — Science",
                        "https://rss.nytimes.com/services/xml/rss/nyt/Science.xml",
                        "https://www.nytimes.com/section/science", "science", "en", "us", "NYT Science."),
                f("npr", "NPR News",
                        "https://feeds.npr.org/1001/rss.xml",
                        "https://www.npr.org/", "general", "en", "us", "NPR."),
                f("aljazeera", "Al Jazeera English",
                        "https://www.aljazeera.com/xml/rss/all.xml",
                        "https://www.aljazeera.com/", "general", "en", "qa", "Al Jazeera."),
                f("ap", "Associated Press",
                        "https://feeds.apnews.com/rss/apf-topnews",
                        "https://apnews.com/", "general", "en", "us", "AP Top News."),
                f("reuters", "Reuters",
                        "https://www.reutersagency.com/feed/?best-topics=business-finance&post_type=best",
                        "https://www.reuters.com/", "business", "en", "us", "Reuters (agency feed)."),
                f("cnn", "CNN International",
                        "http://rss.cnn.com/rss/edition.rss",
                        "https://edition.cnn.com/", "general", "en", "us", "CNN International."),
                f("economist", "The Economist",
                        "https://www.economist.com/the-world-this-week/rss.xml",
                        "https://www.economist.com/", "business", "en", "gb", "The Economist."),
                f("ft", "Financial Times",
                        "https://www.ft.com/rss/home",
                        "https://www.ft.com/", "business", "en", "gb", "Financial Times."),
                f("washingtonpost", "Washington Post — World",
                        "https://feeds.washingtonpost.com/rss/world",
                        "https://www.washingtonpost.com/", "general", "en", "us", "Washington Post."),

                // --- Tech / science EN ---
                f("verge", "The Verge",
                        "https://www.theverge.com/rss/index.xml",
                        "https://www.theverge.com/", "technology", "en", "us", "The Verge."),
                f("wired", "Wired",
                        "https://www.wired.com/feed/rss",
                        "https://www.wired.com/", "technology", "en", "us", "Wired."),
                f("arstechnica", "Ars Technica",
                        "https://feeds.arstechnica.com/arstechnica/index",
                        "https://arstechnica.com/", "technology", "en", "us", "Ars Technica."),
                f("hn", "Hacker News",
                        "https://hnrss.org/frontpage",
                        "https://news.ycombinator.com/", "technology", "en", "us", "Hacker News."),
                f("slashdot", "Slashdot",
                        "https://rss.slashdot.org/Slashdot/slashdotMain",
                        "https://slashdot.org/", "technology", "en", "us", "Slashdot."),
                f("nature", "Nature",
                        "https://www.nature.com/nature.rss",
                        "https://www.nature.com/", "science", "en", "gb", "Nature."),
                f("sciencedaily", "ScienceDaily",
                        "https://www.sciencedaily.com/rss/all.xml",
                        "https://www.sciencedaily.com/", "science", "en", "us", "ScienceDaily."),
                f("physorg", "Phys.org",
                        "https://phys.org/rss-feed/",
                        "https://phys.org/", "science", "en", "us", "Phys.org."),
                f("nasa", "NASA Breaking News",
                        "https://www.nasa.gov/rss/dyn/breaking_news.rss",
                        "https://www.nasa.gov/", "science", "en", "us", "NASA."),
                f("esa", "ESA",
                        "https://www.esa.int/rssfeed/Our_Activities/Space_News",
                        "https://www.esa.int/", "science", "en", "eu", "European Space Agency."),
                f("space", "Space.com",
                        "https://www.space.com/feeds/all",
                        "https://www.space.com/", "science", "en", "us", "Space.com."),
                f("arxiv-cs", "arXiv cs.AI (recent)",
                        "https://rss.arxiv.org/rss/cs.AI",
                        "https://arxiv.org/list/cs.AI/recent", "science", "en", "us",
                        "arXiv Artificial Intelligence."),

                // --- DE / ES / IT ---
                f("spiegel", "Der Spiegel",
                        "https://www.spiegel.de/schlagzeilen/index.rss",
                        "https://www.spiegel.de/", "general", "de", "de", "Der Spiegel."),
                f("zeit", "Die Zeit",
                        "https://newsfeed.zeit.de/index",
                        "https://www.zeit.de/", "general", "de", "de", "Die Zeit."),
                f("tagesschau", "Tagesschau",
                        "https://www.tagesschau.de/xml/rss2/",
                        "https://www.tagesschau.de/", "general", "de", "de", "Tagesschau."),
                f("elpais", "El País",
                        "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",
                        "https://elpais.com/", "general", "es", "es", "El País."),
                f("elmundo", "El Mundo",
                        "https://e00-elmundo.uecdn.es/elmundo/rss/portada.xml",
                        "https://www.elmundo.es/", "general", "es", "es", "El Mundo."),
                f("repubblica", "la Repubblica",
                        "https://www.repubblica.it/rss/homepage/rss2.0.xml",
                        "https://www.repubblica.it/", "general", "it", "it", "la Repubblica."),
                f("ansa", "ANSA",
                        "https://www.ansa.it/sito/ansait_rss.xml",
                        "https://www.ansa.it/", "general", "it", "it", "ANSA."),
                f("corriere", "Corriere della Sera",
                        "https://xml2.corriereobjects.it/rss/homepage.xml",
                        "https://www.corriere.it/", "general", "it", "it", "Corriere della Sera."),

                // --- Weather / misc useful ---
                f("meteofrance", "Météo-France — Actualités",
                        "https://meteofrance.com/rss",
                        "https://meteofrance.com/", "science", "fr", "fr", "Actualités Météo-France."),
                f("who", "OMS / WHO news",
                        "https://www.who.int/rss-feeds/news-english.xml",
                        "https://www.who.int/", "health", "en", "ch", "World Health Organization."),
                f("un", "UN News",
                        "https://news.un.org/feed/subscribe/en/news/all/rss.xml",
                        "https://news.un.org/", "general", "en", "us", "UN News.")
        );
    }

    private static RssFeed f(String id, String name, String url, String website,
                             String category, String language, String country, String description) {
        return new RssFeed(id, name, url, website, category, language, country, description);
    }
}
