package com.pat.config;

import java.util.Map;
import java.util.Optional;

/**
 * {@code @Value("${key:default}")} fallbacks in Java — used when the key is absent from
 * application.properties / environment.
 */
public final class PatToolParameterCodeDefaults {

    private PatToolParameterCodeDefaults() {}

    /** Keys that must be set in application.properties (no {@code :default} in {@code @Value}). */
    public static final java.util.Set<String> REQUIRED_IN_PROPERTIES = java.util.Set.of(
            "keycloak.auth-server-url",
            "keycloak.realm",
            "keycloak.resource",
            "keycloak.credentials.secret",
            "openai.api",
            "openai.assistant.model",
            "openai.assistant.max-tokens",
            "openai.billing.credit-grants-url",
            "app.arduino.ip",
            "app.esp32.1.ip",
            "file.storage.base-path",
            "app.mailsentfrom",
            "app.mailsentto",
            "app.sendmail"
    );

    private static final Map<String, String> DEFAULTS = Map.ofEntries(
            Map.entry("spring.data.mongodb.port", "27017"),
            Map.entry("spring.data.mongodb.database", "rando"),
            Map.entry("spring.data.mongodb.uri", ""),
            Map.entry("spring.data.mongodb.host", ""),
            Map.entry("app.uploaddir", "C:\\temp"),
            Map.entry("app.imagemaxsizekb", "500"),
            Map.entry("keycloak.client-id", "tutorial-frontend"),
            Map.entry("app.cors.allowed-origins",
                    "http://localhost:4200,http://127.0.0.1:4200,http://localhost:8000,http://127.0.0.1:8000"),
            Map.entry("pat.passive-probe.allow-private-targets", "false"),
            Map.entry("pat.passive-probe.max-redirects", "5"),
            Map.entry("pat.passive-probe.connect-timeout-seconds", "5"),
            Map.entry("pat.passive-probe.request-timeout-seconds", "15"),
            Map.entry("app.mailsentfrom", ""),
            Map.entry("app.mailsentto", ""),
            Map.entry("app.sendmail", "false"),
            Map.entry("assistant.provider", "openai"),
            Map.entry("openai.key", ""),
            Map.entry("openai.provider", "OpenAI"),
            Map.entry("openai.http.connect-timeout-seconds", "300"),
            Map.entry("openai.http.read-timeout-seconds", "300"),
            Map.entry("anthropic.key", ""),
            Map.entry("anthropic.api", "https://api.anthropic.com/v1/messages"),
            Map.entry("anthropic.model", "claude-sonnet-4-6"),
            Map.entry("anthropic.max-tokens", "8192"),
            Map.entry("anthropic.provider-label", "Anthropic"),
            Map.entry("anthropic.version", "2023-06-01"),
            Map.entry("anthropic.web-search-tool-type", "web_search_20250305"),
            Map.entry("anthropic.web-search-max-uses", "0"),
            Map.entry("anthropic.http.connect-timeout-seconds", "300"),
            Map.entry("anthropic.http.read-timeout-seconds", "300"),
            Map.entry("gemini.key", ""),
            Map.entry("gemini.api", "https://generativelanguage.googleapis.com/v1beta"),
            Map.entry("gemini.model", "gemini-2.0-flash"),
            Map.entry("gemini.image-generation-model", "gemini-2.5-flash-image"),
            Map.entry("gemini.max-output-tokens", "16384"),
            Map.entry("gemini.thinking-budget", "0"),
            Map.entry("gemini.provider-label", "Google"),
            Map.entry("gemini.web-search-legacy-model-prefixes", "gemini-1.5,gemini-1.0"),
            Map.entry("gemini.http.connect-timeout-seconds", "300"),
            Map.entry("gemini.http.read-timeout-seconds", "300"),
            Map.entry("mistral.key", ""),
            Map.entry("mistral.api", "https://api.mistral.ai/v1/chat/completions"),
            Map.entry("mistral.model", "mistral-large-latest"),
            Map.entry("mistral.max-tokens", "8192"),
            Map.entry("mistral.provider-label", "Mistral"),
            Map.entry("mistral.http.connect-timeout-seconds", "300"),
            Map.entry("mistral.http.read-timeout-seconds", "300"),
            Map.entry("globe.proxy.http.connect-timeout-seconds", "10"),
            Map.entry("globe.proxy.http.read-timeout-seconds", "90"),
            Map.entry("globe.iss.trace.retention.days", "30"),
            Map.entry("globe.iss.trace.sample-interval.seconds", "60"),
            Map.entry("globe.iss.trace.max-display-points", "8000"),
            Map.entry("globe.iss.trace.display.limit.points", "1000"),
            Map.entry("globe.iss.trace.display.limit.enabled-default", "true"),
            Map.entry("globe.iss.trace.background.enabled-default", "false"),
            Map.entry("globe.iss.trace.background.interval.seconds", "900"),
            Map.entry("globe.iss.alert.lead-minutes", "30"),
            Map.entry("globe.iss.alert.zone", "Europe/Paris"),
            Map.entry("globe.iss.alert.reminder-mail.ui-base-url", "https://www.patrickdeschamps.com"),
            Map.entry("govee.api.key", ""),
            Map.entry("govee.thermometer.auto.refresh.enabled", "true"),
            Map.entry("govee.thermometer.auto.refresh.cron", "0 */10 * * * ?"),
            Map.entry("govee.thermometer.history.retention.days", "30"),
            Map.entry("app.iot-proxy.max-response-bytes", "52428800"),
            Map.entry("app.iot-proxy.max-request-body-bytes", "10485760"),
            Map.entry("app.iot-proxy.max-rewrite-body-bytes", "5242880"),
            Map.entry("app.iot-proxy.redirect-max-hops", "10"),
            Map.entry("app.iot-proxy.open-token-hmac-secret", ""),
            Map.entry("app.iot-proxy.open-token-validity-seconds", "300"),
            Map.entry("app.connection.email.enabled", "false"),
            Map.entry("app.connection.email.min-interval-minutes", "30"),
            Map.entry("openai.responses.api", ""),
            Map.entry("openai.mcp.server-label", ""),
            Map.entry("openai.mcp.server-url", ""),
            Map.entry("openai.mcp.authorization", ""),
            Map.entry("app.cern.opendata-portal-base", "https://opendata.cern.ch"),
            Map.entry("app.nager.api-base", "https://date.nager.at/api/v3"),
            Map.entry("app.frankfurter.api-base", "https://api.frankfurter.app"),
            Map.entry("app.ip.geolocation.cache.max-size", "5000"),
            Map.entry("app.ip.geolocation.cache.ttl-hours", "24"),
            Map.entry("app.exception.tracking.retention-hours", "168"),
            Map.entry("app.exception.tracking.max-entries-per-ip", "1000"),
            Map.entry("app.router.username", "admin"),
            Map.entry("app.router.password", ""),
            Map.entry("app.router.ip", ""),
            Map.entry("app.network.scan.scheduler.enabled", "false"),
            Map.entry("app.network.scan.scheduler.cron", "0 */10 * * * ?"),
            Map.entry("openweathermap.api.key", ""),
            Map.entry("meteofrance.api.token", ""),
            Map.entry("meteofrance.clim.api.token", ""),
            Map.entry("meteofrance.oauth.application-id", ""),
            Map.entry("meteofrance.radar.base.url", "https://public-api.meteofrance.fr/public/DPRadar/v1"),
            Map.entry("meteofrance.radar.wms.url", "https://geoservices.meteofrance.fr/services/WMS"),
            Map.entry("meteofrance.radar.wms.layer", "RADARURANCE400M"),
            Map.entry("meteofrance.radar.wms.enabled", "false"),
            Map.entry("meteofrance.radar.refresh.seconds", "60"),
            Map.entry("meteofrance.clim.base.url", "https://public-api.meteofrance.fr/public/DPClim/v1"),
            Map.entry("thunderforest.api.key", ""),
            Map.entry("ign.api.key", ""),
            Map.entry("loto.archive.base-url", "https://www.lesbonsnumeros.com"),
            Map.entry("euromillions.import.directory", ""),
            Map.entry("euromillions.fdj.historique-url",
                    "https://www.fdj.fr/jeux-de-tirage/euromillions-my-million/historique"),
            Map.entry("euromillions.fdj.archive-download-attribute", "euromillions_202002"),
            Map.entry("euromillions.ai.min-draw-date", "2020-01-01"),
            Map.entry("opensky.base-url", "https://opensky-network.org/api"),
            Map.entry("opensky.token-url",
                    "https://auth.opensky-network.org/auth/realms/opensky-network/protocol/openid-connect/token"),
            Map.entry("opensky.client-id", ""),
            Map.entry("opensky.client-secret", ""),
            Map.entry("opensky.all-states-cache-seconds", "30"),
            Map.entry("opensky.all-states-stale-max-seconds", "900"),
            Map.entry("flight.adsbdb.enabled", "true"),
            Map.entry("flight.adsbdb.base-url", "https://api.adsbdb.com/v0"),
            Map.entry("app.cern.opendata-api-base", "https://opendata.cern.ch/api"),
            Map.entry("app.cern.repository-api-base", "https://repository.cern/api"),
            Map.entry("app.cern.zenodo-api-base", "https://zenodo.org/api"),
            Map.entry("app.chem.pubchem-rest-base", "https://pubchem.ncbi.nlm.nih.gov/rest/pug"),
            Map.entry("app.chem.pubchem-autocomplete-base", "https://pubchem.ncbi.nlm.nih.gov/rest/autocomplete"),
            Map.entry("app.stellarium.web-base", "https://stellarium-web.org"),
            Map.entry("app.stellarium.noctuasky-api-base", "https://api.noctuasky.com/api/v1"),
            Map.entry("app.stellarium.freegeoip-base", "https://freegeoip.stellarium.org"),
            Map.entry("app.stellarium.patool-viewer-base", ""),
            Map.entry("app.twelvedata.api-base", "https://api.twelvedata.com"),
            Map.entry("app.twelvedata.api-key", "demo"),
            Map.entry("app.coingecko.api-base", "https://api.coingecko.com/api/v3"),
            Map.entry("app.coingecko.api-key", ""),
            Map.entry("app.coingecko.plan", "demo"),
            Map.entry("newsapi.api.base.url", "https://newsapi.org/v2"),
            Map.entry("newsapi.api.key", ""),
            Map.entry("newsapi.api.keys", ""),
            Map.entry("newsapi.cache.ttl.minutes", "5"),
            Map.entry("newsapi.cache.ttl.empty.minutes", "60"),
            Map.entry("newsapi.ticker.enabled.default", "false"),
            Map.entry("newsapi.default.country", "fr"),
            Map.entry("newsapi.default.language", "fr"),
            Map.entry("newsapi.quota.daily", "100"),
            Map.entry("newsdata.api.base.url", "https://newsdata.io/api/1"),
            Map.entry("newsdata.api.key", ""),
            Map.entry("newsdata.api.keys", ""),
            Map.entry("newsdata.cache.ttl.minutes", "5"),
            Map.entry("newsdata.cache.ttl.empty.minutes", "60"),
            Map.entry("newsdata.ticker.enabled.default", "false"),
            Map.entry("newsdata.default.country", "fr"),
            Map.entry("newsdata.default.language", "fr"),
            Map.entry("newsdata.quota.daily", "200"),
            Map.entry("app.cache.persistence.restore-on-startup", "true"),
            Map.entry("app.cache.persistence.dir", "./cache"),
            Map.entry("app.cache.persistence.filename", "image-cache.dat"),
            Map.entry("app.memory.warning-threshold", "85"),
            Map.entry("app.memory.critical-threshold", "90"),
            Map.entry("app.image.compression.max-concurrency", "10"),
            Map.entry("app.image.compression.cache.max-entries", "3000"),
            Map.entry("app.image.compression.cache.max-size-mb", "200"),
            Map.entry("app.image.compression.cache.ttl", "PT2H"),
            Map.entry("app.video.ffmpeg.path", "ffmpeg"),
            Map.entry("app.video.compression.enabled", "false"),
            Map.entry("app.video.compression.max-concurrency", "2"),
            Map.entry("app.calendar.morning-reminder.enabled", "true"),
            Map.entry("app.calendar.morning-reminder.zone", "Europe/Paris"),
            Map.entry("app.calendar.reminder-mail.ui-base-url", "https://www.patrickdeschamps.com"),
            Map.entry("app.holiday-ui-translate.enabled", "true"),
            Map.entry("app.holiday-ui-translate.cache-ttl-hours", "168"),
            Map.entry("app.discussion.default.id", ""),
            Map.entry("app.websocket.max-connections", "1000"),
            Map.entry("app.websocket.connection-max-age-minutes", "30"),
            Map.entry("app.connection-logs.excluded-users", "patricou"),
            Map.entry("openweathermap.api.base.url", "https://api.openweathermap.org/data/2.5")
    );

    public static Optional<String> codeDefault(String key) {
        if (key == null || !DEFAULTS.containsKey(key)) {
            return Optional.empty();
        }
        return Optional.of(DEFAULTS.get(key));
    }

    public static boolean isRequiredInProperties(String key) {
        return key != null && REQUIRED_IN_PROPERTIES.contains(key);
    }
}
